In [44]:
import pandas as pd
import numpy as np
from mpl_toolkits import mplot3d

In [32]:
from matplotlib import pyplot as plt

In [33]:
data = pd.read_csv('Data.csv',delimiter=',')

In [35]:
x1 = np.genfromtxt('Data.csv',delimiter=',')
x1

array([[-1.4337200e-01, -2.3010860e+00,  8.7689575e+01],
       [-7.1960000e-02, -2.3604130e+00,  8.7642151e+01],
       [-9.5306000e-02, -2.2468690e+00,  8.7752205e+01],
       ...,
       [-1.0816000e-01, -1.8461970e+00,  8.8140244e+01],
       [ 1.0991820e+00, -9.3559600e-01,  8.8531769e+01],
       [ 1.1227480e+00, -9.5471200e-01,  8.8527657e+01]])

In [36]:
np.cross(x1[0],x1[1])

array([5.31148612, 6.25528866, 0.17283098])

In [37]:
np.cross(x1[1],x1[2])

array([-10.21101329,  -2.03817417,  -0.06327683])

In [41]:
crossArray = []
for i,j in enumerate(x1[0:2146]):
    crossArray.append(np.cross(x1[i],x1[i+1]))
crossArray
    
    

[array([5.31148612, 6.25528866, 0.17283098]),
 array([-10.21101329,  -2.03817417,  -0.06327683]),
 array([-38.31894289,  -0.72527545,  -0.06018794]),
 array([   31.41169871, -7874.15802441,  -162.58284286]),
 array([  0.61149931, -35.63075288,  72.63350503]),
 array([ -0.79984587,  56.13195173, -28.5968664 ]),
 array([ -1.2540458 ,  82.08616357, -51.1739986 ]),
 array([  0.66507312, -68.63497607,  23.11101658]),
 array([ -45.1346698 , 7794.76878924,  205.41646339]),
 array([4.2909524 , 6.23606093, 0.17130648]),
 array([-9.79342208, -3.09766856, -0.09121225]),
 array([-38.61553275,  -0.09069455,  -0.04871718]),
 array([   31.43146348, -7876.56709448,  -162.66215159]),
 array([  0.6105766 , -37.48934055,  72.71967919]),
 array([ -0.80682977,  57.36273679, -28.87409396]),
 array([ -1.25433794,  83.48127858, -51.10944021]),
 array([  0.66428009, -67.92486334,  23.28051624]),
 array([ -45.1367971, 7795.2503702,  205.275702 ]),
 array([4.4283366 , 6.9001774 , 0.18945942]),
 array([-9.6293027